reporting/urls.py
from django.conf.urls.defaults import *

urlpatterns = patterns('reporting.views',
    (r'^$', 'index.index'),
    (r'^hours/$', 'hours.index'),
    (r'^hours/(?P<project_name>[a-zA-Z0-9\ \-_]*)/$', 'hours.choose_details'),
    (r'^hours/(?P<project_name>[a-zA-Z0-9\ \-_]*)/report/$', 'hours.do_report'),
    (r'^time-spent/$', 'time_spent.index'),
    (r'^time-spent/(?P<project_name>[a-zA-Z0-9\ \-_]*)/$', 'time_spent.choose_details'),
    (r'^time-spent/(?P<project_name>[a-zA-Z0-9\ \-_]*)/report/$', 'time_spent.do_report'),
    (r'^client-report/$', 'client_report.index'),
    (r'^client-report/(?P<project_name>[a-zA-Z0-9\ \-_]*)/$', 'client_report.do_report'),
    (r'^client-report/(?P<project_name>[a-zA-Z0-9\ \-_]*)/(?P<trac_ticket_id>\d+)/$', 'client_report.edit_ticket'),
    (r'^work-todo/$', 'work_todo.index'),
    (r'^work-todo/(?P<project_name>[a-zA-Z0-9\ \-_]*)/$', 'work_todo.do_report'),
    (r'^current-tickets/$', 'current_tickets.index'),
    (r'^current-tickets/(?P<developer_name>[a-zA-Z0-9\ \-_]*)/$', 'current_tickets.do_report'),
    (r'^todo/$', 'todo.index'),
    (r'^todo/action/$', 'todo.action'),
)

urls.py
from django.conf.urls.defaults import *

# Uncomment the next two lines to enable the admin:
from django.contrib import admin
admin.autodiscover()

urlpatterns = patterns('',
    (r'^$', 'board.views.index.redirect_to_board'),
    (r'^board/', include('board.urls')),
    (r'^reporting/', include('reporting.urls')),
    (r'^client/', include('client.urls')),
    (r'^admin/', include('board.admin.urls')),

    # Uncomment the admin/doc line below and add 'django.contrib.admindocs' 
    # to INSTALLED_APPS to enable admin documentation:
    # (r'^admin/doc/', include('django.contrib.admindocs.urls')),

    # Uncomment the next line to enable the admin:
    (r'^admin/(.*)', admin.site.root),
)

reporting/models.py
from django.db import models

# Create your models here.

reporting/forms.py
from board.models import Cost, Ticket
from django import forms

class CostForm(forms.ModelForm):
    class Meta:
        model = Cost

class SearchTimeBookingForm(forms.Form):
    developer = forms.ChoiceField(required=False)
    type = forms.ChoiceField(required=False)
    start = forms.DateField()
    end = forms.DateField()

def list_to_choices(list):
    choices = []
    for item in list:
        choices += [(item, item)]
    return choices

reporting/views/client_report.py
from django.views.generic.simple import direct_to_template
from django.core.exceptions import ObjectDoesNotExist
from django.http import HttpResponseRedirect
from django.conf import settings
from board.models import *
from board.managers import PersonManager
from reporting.forms import CostForm

def index(request):
    """
    Displays a list of all available projects, allowing the user to pick one.
    """
    
    # If they're logged in and their name matches a project, direct them to it, because we don't want to give them the
    # option of viewing other projects. Only admins should see all projects. Denied to the rest.
    person = Person.objects.authenticate(request)
    if person == None:
        return HttpResponseRedirect('/') # Should never happen.
    if not person.is_staff:
        return HttpResponseRedirect('/reporting/client-report/' + person.username + '/')
    
    projects = Project.objects.getAllProjectNames()
    data = {'projects': projects, 'allow_all_projects': False}
    return direct_to_template(request, 'reporting/choose-project.html', data)

def do_report(request, project_name):
    """
    Finds the tickets which match the data given by the user, then displays the appropriate data.
    """
    
    # Check that the project name matches their user name, since we don't want to allow them to view other projects.
    person = Person.objects.authenticate(request)
    if person == None:
        return HttpResponseRedirect('/') # Should never happen.
    if not person.is_staff and project_name != person.username:
        return HttpResponseRedirect('/reporting/client-report/')
    
    can_edit = False
    if person.is_staff:
        can_edit = True
    
    ticket_fields = ['trac_ticket_id', 'title', 'description', 'status', 'creation_date']
    result = Ticket.objects.getFilteredTickets(request, project_name, ticket_fields)
    tickets = result[0]
    filter_data = result[1]
    
    # Tally up the votes to see who won.
    total_hours = 0
    total_cost = 0
    for ticket in tickets:
        total_hours = total_hours + ticket.actual_time
        total_cost = total_cost + ticket.getCostSoFar()
    
    # Whether or not the "Time Spent" column should be shown.
    show_time_spent = False
    if len(tickets) > 0:
        show_time_spent = tickets[0].project.show_total_hours
    
    data = {'tickets': tickets,
        'ticket_count': len(tickets),
        'total_hours': total_hours,
        'total_cost': total_cost,
        'project_name': project_name,
        'show_time_spent': show_time_spent,
        'can_edit': can_edit,
        'filter_data': filter_data,
        'path_to_trac': settings.PATH_TO_TRAC,
    }
    return direct_to_template(request, 'reporting/client-report.html', data)

def edit_ticket(request, project_name, trac_ticket_id):
    """
    Allows users to edit the cost of tickets.
    """
    
    person = Person.objects.authenticate(request)
    if person == None:
        return HttpResponseRedirect('/') # Should never happen.
    if not person.is_staff:
        return HttpResponseRedirect('/reporting/client-report/' + person.username + '/')
    
    try:
        ticket = Ticket.objects.get(project__name = project_name, trac_ticket_id = trac_ticket_id)
    except ObjectDoesNotExist:
        return HttpResponseRedirect('/reporting/client-report/' + project_name + '/')
    
    # Handle the form.
    if request.method == 'POST':
        form = CostForm(request.POST)
        if form.is_valid():
            if ticket.cost != None:
                print "Existing cost"
                ticket.cost.per_hour = form.cleaned_data['per_hour']
                ticket.cost.override_total = form.cleaned_data['override_total']
                ticket.cost.save()
            else:
                print "New cost"
                cost = Cost()
                cost.per_hour = form.cleaned_data['per_hour']
                cost.override_total = form.cleaned_data['override_total']
                cost.save()
                ticket.cost = cost
            
            ticket.save()
            return HttpResponseRedirect('/reporting/client-report/' + project_name + '/')
    else:
        cost = ticket.cost
        if cost == None:
            cost = Cost()
        form = CostForm(instance = cost)
    
    data = {'ticket': ticket, 'form': form, 'project_name': project_name}
    return direct_to_template(request, 'reporting/client-report-ticket-edit.html', data)

reporting/views/current_tickets.py
from django.views.generic.simple import direct_to_template
from django.conf import settings
from board.models import *

def index(request):
    """
    Displays a list of all available projects, allowing the user to pick one.
    """
    
    developers = Person.objects.getAllDevelopers()
    data = {'developers': developers, 'developer_count': len(developers)}
    return direct_to_template(request, 'reporting/current-tickets.html', data)

def do_report(request, developer_name):
    """
    Shows all tickets for the chosen developer.
    """
    
    projects = []
    tickets = Ticket.objects.fetchTicketsForDeveloper(developer_name)
    for ticket in tickets:
        try:
            if projects.index(ticket.project.name):
                continue
        except:
            projects.append(ticket.project.name)
        
    data = {'developer_name': developer_name, 'tickets': tickets, 'projects': projects, 'path_to_trac': settings.PATH_TO_TRAC}
    return direct_to_template(request, 'reporting/current-tickets-report.html', data)

reporting/views/hours.py
from django.views.generic.simple import direct_to_template
from django.core.exceptions import ObjectDoesNotExist
from django.conf import settings
from board.models import *
from reporting.forms import list_to_choices, SearchTimeBookingForm
from django.http import HttpResponseRedirect
from django.core.urlresolvers import reverse

def index(request):
    """
    Displays a list of all available projects, allowing the user to pick one.
    """
    
    projects = Project.objects.getAllProjectNames()
    data = {'projects': projects, 'allow_all_projects': True}
    return direct_to_template(request, 'reporting/choose-project.html', data)

def choose_details(request, project_name):
    """
    Once a project has been selected, this allows the user to choose which developer, which ticket type and the dates
    between which the ticket should fall in to.
    """
    
    developers = []
    if project_name == 'all':
        developers = Person.objects.getAllDevelopers()
    else:
        tickets = Ticket.objects.filter(project__name = project_name)
        for ticket in tickets:
            # Only add developers who are not already in the list.
            try:
                index = developers.index(ticket.assigned_person.username)
                continue
            except ValueError:
                developers.append(ticket.assigned_person.username)
            
            # Get the names of all developers who have made changes to the ticket.
            change_authors = ticket.getChangeAuthors()
            for change_author in change_authors:
                try:
                    index = developers.index(change_author)
                    continue
                except ValueError:
                    developers.append(change_author)
        developers.sort()

    if '' not in developers:
        developers.insert(0, '')

    # Get the different types of tickets.
    ticket_types = ['', 'defect', 'enhancement', 'task', 'support']
    
    SearchTimeBookingForm.base_fields['developer'].choices = list_to_choices(developers)
    SearchTimeBookingForm.base_fields['type'].choices = list_to_choices(ticket_types)

    if request.method == 'POST':
        form = SearchTimeBookingForm(request.POST)
        if form.is_valid():
            return do_report(request, project_name)
    
    else:
        form = SearchTimeBookingForm()

    data = {'form': form}

    return direct_to_template(request, 'reporting/choose-details.html', data)

def do_report(request, project_name):
    """
    Finds the tickets which match the data given by the user, then display the appropriate data.
    """
    
    try:
        developer = request.POST['developer']
        ticket_type = request.POST['type']
        start_date = request.POST['start']
        end_date = request.POST['end']
    except KeyError, message:
        url = reverse('reporting.views.hours.choose_details', kwargs={'project_name': project_name})
        return HttpResponseRedirect(url)
    
    # Find all changes which meet the criteria.
    changes = TicketChange.objects.fetchChanges(project_name, developer, ticket_type, start_date, end_date)
    
    total_hours = 0
    for change in changes:
        total_hours = total_hours + change.hours
    
    data = {'developer': developer, 'project_name': project_name, 'total_hours': total_hours, 'changes': changes, 'path_to_trac': settings.PATH_TO_TRAC}
    return direct_to_template(request, 'reporting/hours-report.html', data)

reporting/views/index.py
from django.views.generic.simple import direct_to_template

def index(request):
    return direct_to_template(request, 'reporting/index.html')

reporting/views/time_spent.py
from django.views.generic.simple import direct_to_template
from django.core.exceptions import ObjectDoesNotExist
from django.conf import settings
from board.models import *

def index(request):
    """
    Displays a list of all available projects, allowing the user to pick one.
    """
    
    projects = Project.objects.getAllProjectNames()
    data = {'projects': projects, 'allow_all_projects': False}
    return direct_to_template(request, 'reporting/choose-project.html', data)

def choose_details(request, project_name, error = ''):
    """
    Once a project has been selected, this allows the user to choose which developer, which ticket type and the dates
    between which the ticket should fall in to.
    """
    
    developers = []
    if project_name == 'all':
        developers = Person.objects.getAllDevelopers()
    else:
        tickets = Ticket.objects.filter(project__name = project_name)
        for ticket in tickets:
            # Only add developers who are not already in the list.
            try:
                index = developers.index(ticket.assigned_person.username)
                continue
            except ValueError:
                developers.append(ticket.assigned_person.username)
            
            # Get the names of all developers who have made changes to the ticket.
            change_authors = ticket.getChangeAuthors()
            for change_author in change_authors:
                try:
                    index = developers.index(change_author)
                    continue
                except ValueError:
                    developers.append(change_author)
        developers.sort()
    
    # Get the different types of tickets.
    ticket_types = ['defect', 'enhancement', 'task', 'support']
    
    # Pass it off to the template.
    data = {'developers': developers, 'ticket_types': ticket_types}
    if error != '':
        data['error'] = error
    return direct_to_template(request, 'reporting/choose-details.html', data)

def do_report(request, project_name):
    """
    Finds the tickets which match the data given by the user, then display the appropriate data.
    """
    
    try:
        developer = request.POST['developer']
        ticket_type = request.POST['ticket_type']
        start_date = request.POST['start_date']
        end_date = request.POST['end_date']
    except KeyError, message:
        return choose_details(request, project_name, 'Missing one or more fields')
    
    # Find all changes which meet the criteria.
    tickets = Ticket.objects.fetchTickets(project_name, developer, ticket_type, start_date, end_date)
    
    data = {'developer': developer, 'project_name': project_name, 'tickets': tickets, 'path_to_trac': settings.PATH_TO_TRAC}
    return direct_to_template(request, 'reporting/time-spent-report.html', data)

reporting/views/todo.py
from django.views.generic.simple import direct_to_template
from django.core.exceptions import ObjectDoesNotExist
from django.http import HttpResponseRedirect
from django.conf import settings
from board.models import *

def index(request):
    """
    Displays a list of all available projects, allowing the user to pick one.
    """
    
    projects = Project.objects.getAllProjectNames()
    data = {'projects': projects, 'project_count': len(projects)}
    return direct_to_template(request, 'reporting/todo.html', data)

def action(request):
    """
    Redirect the user to the Trac instance for the chosen project.
    """
    
    project = ''
    try:
        project = request.POST['project_name']
        if request.POST.has_key('new_ticket'):
            action = 'new'
        elif request.POST.has_key('view_tickets'):
            action = 'view'
    except:
        pass
    
    if project != '':
        if action == 'new':
            return HttpResponseRedirect(settings.PATH_TO_TRAC + project + '/newticket')
        elif action == 'view':
            return HttpResponseRedirect(settings.PATH_TO_TRAC + project + '/report/1')
    
    return HttpResponseRedirect('/reporting/todo/')

reporting/views/work_todo.py
from django.views.generic.simple import direct_to_template
from django.core.exceptions import ObjectDoesNotExist
from django.conf import settings
from board.models import *

def index(request):
    """
    Displays a list of all available projects, allowing the user to pick one.
    """
    
    projects = Project.objects.getAllProjectNames()
    data = {'projects': projects, 'allow_all_projects': False}
    return direct_to_template(request, 'reporting/choose-project.html', data)

def do_report(request, project_name):
    """
    Show a list of tickets that are open.
    """
    
    ticket_fields = ['trac_ticket_id', 'title', 'description', 'status', 'creation_date']
    result = Ticket.objects.getFilteredTickets(request, project_name, ticket_fields)
    tickets = result[0].exclude(status__in = ['closed', 'duplicate', 'invalid'])
    filter_data = result[1]
    
    data = {'project_name': project_name, 'tickets': tickets, 'ticket_count': len(tickets), 'path_to_trac': settings.PATH_TO_TRAC, 'filter_data': filter_data}
    return direct_to_template(request, 'reporting/work-todo.html', data)

templates/reporting/base.html
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Strict//EN"
    "http://www.w3.org/TR/xhtml1/DTD/xhtml1-strict.dtd">

<html xmlns="http://www.w3.org/1999/xhtml" xml:lang="en">
  <head>
    <meta http-equiv="content-type" content="application/xhtml+xml; charset=utf-8" />
    <meta name="generator" content="vim" />
    {% block css %}{% endblock %}
    {% block javascript %}{% endblock %}
    <title>PalePurple Virtual Planning Board</title>
  </head>

  <body>
    {% include "reporting/menu.html" %}
    {% block content %}{% endblock %}
  </body>
</html>

templates/reporting/choose-details.html
{% extends "reporting/base.html" %}

{% block css %}
<link rel="stylesheet" href="{{ MEDIA_URL }}reporting/css/base.css" type="text/css" />
<link type="text/css" href="{{ MEDIA_URL }}reporting/css/humanity/jquery-ui-1.7.1.custom.css" rel="stylesheet" />
{% endblock %}

{% block javascript %}
<script type="text/javascript" src="{{ MEDIA_URL }}reporting/js/jquery-1.3.2.min.js"></script>
<script type="text/javascript" src="{{ MEDIA_URL }}reporting/js/jquery-ui-1.7.1.custom.min.js"></script>
<script type="text/javascript">
    $(function(){
        $('#id_start, #id_end').datepicker({ dateFormat: 'yy-mm-dd' });
    });
</script>
{% endblock %}

{% block content %}


<div id="project_details">
    <h1>Search For Time Bookings:</h1>
{% ifnotequal error '' %}
    <h3 class='error'>{{ error }}</h3>
{% endifnotequal %}
    <form action="" method="post">
        <ul>
            {% for field in form %}
            <li>{{ field.errors }}{{ field.label_tag }}{{ field }}</li>
            {% endfor %}
            <li><input type="submit" name="submit" value="Report!" /></li>
        </ul>
    </form>
</div>
{% endblock %}

templates/reporting/choose-project.html
{% extends "reporting/base.html" %}

{% block css %}
<link rel="stylesheet" href="{{ MEDIA_URL }}reporting/css/base.css" type="text/css" />
{% endblock %}

{% block javascript %}
{% endblock %}

{% block content %}
<div id="project_list">
    <h1>Select Project:</h1>
    <ul>
    {% if allow_all_projects %}
        <li class="project_link"><a href="all/">All Projects</a></li>
    {% endif %}
    {% for project in projects %}
        <li class="project_link"><a href="{{ project }}/">{{ project }}</a></li>
    {% endfor %}
    </ul>
</div>
{% endblock %}

templates/reporting/client-report-ticket-edit.html
{% extends "board/base.html" %}

{% block css %}
<link rel="stylesheet" href="{{ MEDIA_URL }}board/css/client_reporting.css" type="text/css" />
<link rel="stylesheet" href="{{ MEDIA_URL }}board/css/colour-scheme.css" type="text/css" />
{% endblock %}

{% block javascript %}
{% endblock %}

{% block content %}
<div id="client_report">
    <h1>Client Report</h1>
    <h3>Edit Ticket's Cost</h3>
    
{% ifnotequal error '' %}
    <h3 class="client_reporting_error">{{ error }}</h3>
{% endifnotequal %}
    
    <form action="" method="post">
        <table>
            <tr>
                <th>Ticket:</th>
                <td><a href="http://trac.palepurple.co.uk/projects/{{ project_name }}/ticket/{{ ticket.trac_ticket_id }}">#{{ ticket.trac_ticket_id }} {{ ticket.title }}</a></td>
            </tr>
            {{ form.as_table }}
            <tr>
                <th colspan="2"><input type="submit" name="submit" value="Save" /></th>
            </tr>
        </table>
    </form>
    
<!--    <form action="" method="post">
        <table>
            <tr>
                <th>Ticket:</th>
                <td><a href="http://trac.palepurple.co.uk/projects/{{ project_name }}/ticket/{{ ticket.trac_ticket_id }}">#{{ ticket.trac_ticket_id }} {{ ticket.title }}</a></td>
            </tr>
            <tr>
                <th>Cost Per Hour:</th>
                <td><input type="text" name="per_hour" value="{{ ticket.cost.per_hour }}" /></td>
            </tr>
            <tr>
                <th>Override Total:</th>
                <td><input type="text" name="override_total" value="{{ ticket.cost.override_total }}" /></td>
            </tr>
            <tr>
                <th colspan="2"><input type="submit" name="submit" value="Save" /></th>
            </tr>
        </table>
    </form>-->
</div>
{% endblock %}

templates/reporting/client-report.html
{% extends "reporting/base.html" %}

{% block css %}
<link rel="stylesheet" href="{{ MEDIA_URL }}reporting/css/base.css" type="text/css" />
{% endblock %}

{% block javascript %}
{% endblock %}

{% block content %}
<div id="report">
    <h1>Client Report</h1>
    {% include "reporting/filter.html" %}
    
{% ifequal ticket_count 0 %}
    <p>No tickets found</p>
{% else %}
    <table>
        <tr>
            <th>Ticket:</th>
            <th>Status:</th>
        {% if show_time_spent %}
            <th>Time Spent:</th>
        {% endif %}
            <th>Cost So Far:</th>
        {% if can_edit %}
            <th>Edit:</th>
        {% endif %}
        </tr>
        
    {% for ticket in tickets %}
        <tr>
            <td><a href="{{ path_to_trac }}{{ project_name }}/ticket/{{ ticket.trac_ticket_id }}">#{{ ticket.trac_ticket_id }} {{ ticket.title }}</a></td>
            <td>{{ ticket.status|capfirst }}</td>
        {% if show_time_spent %}
            <td>{{ ticket.actual_time }}</td>
        {% endif %}
            <td>{{ ticket.getCostSoFar }}</td>
        {% if can_edit %}
            <td><a href="{% url reporting.views.client_report.do_report project_name %}{{ ticket.trac_ticket_id }}/"><img src="{{ MEDIA_URL }}board/images/pencil.png"/></a></td>
        {% endif %}
        </tr>
    {% endfor %}
        
        <tr>
            <td>&nbsp;</td>
            <th>Totals:</th>
        {% if show_time_spent %}
            <td>{{ total_hours }}</td>
        {% endif %}
            <td>{{ total_cost }}</td>
        {% if can_edit %}
            <td>&nbsp;</td>
        {% endif %}
        </tr>
    </table>
{% endifequal %}
</div>
{% endblock %}

templates/reporting/current-tickets-report.html
{% extends "reporting/base.html" %}

{% block css %}
<link rel="stylesheet" href="{{ MEDIA_URL }}reporting/css/base.css" type="text/css" />
{% endblock %}

{% block javascript %}
{% endblock %}

{% block content %}
<div id="developer_tickets_list">
    <h1>Current Open Tickets For "{{ developer_name }}":</h1>
    
{% for project_name in projects %}
    <h3>Tickets for "{{ project_name }}":</h3>
    <table class="project_table">
        <tr>
            <th class="ticket">Ticket:</th>
            <th class="summary">Summary:</th>
        </tr>
    {% for ticket in tickets %}
        {% ifequal project_name ticket.project.name %}
        <tr>
            <td><a href="{{ path_to_trac }}{{ project_name }}/ticket/{{ ticket.trac_ticket_id }}">#{{ ticket.trac_ticket_id }}</a></td>
            <td>{{ ticket.title }}</td>
        </tr>
        {% endifequal %}
    {% endfor %}
    </table>
{% endfor %}
</div>
{% endblock %}

templates/reporting/current-tickets.html
{% extends "reporting/base.html" %}

{% block css %}
<link rel="stylesheet" href="{{ MEDIA_URL }}reporting/css/base.css" type="text/css" />
{% endblock %}

{% block javascript %}
{% endblock %}

{% block content %}
<div id="developer_list">
    <h1>Select Developer:</h1>
{% ifequal developer_count 0 %}
    <p>No developers found</p>
{% else %}
    <ul>
    {% for developer in developers %}
        <li class="developer_link"><a href="{{ developer }}/">{{ developer }}</a></li>
    {% endfor %}
    </ul>
{% endifequal %}
</div>
{% endblock %}

templates/reporting/filter.html
<div id="filter">
    <form id="filter_form" name="filter_form" method="post" action="">
        <table class="filter">
            <tr>
                <th>Filter Results By:</th>
                <td>
                    <select name="filter_by">
                        <option label="ID" value="trac_ticket_id"{% ifequal filter_data.filter_by 'trac_ticket_id' %} selected="selected"{% endifequal %}>ID</option>
                        <option label="Title" value="title"{% ifequal filter_data.filter_by 'title' %} selected="selected"{% endifequal %}>Title</option>
                        <option label="Description" value="description"{% ifequal filter_data.filter_by 'description' %} selected="selected"{% endifequal %}>Description</option>
                        <option label="Status" value="status"{% ifequal filter_data.filter_by 'status' %} selected="selected"{% endifequal %}>Status</option>
                    </select>
                    is
                </td>
                <td>
                    <select name="filter_criteria">
                        <option label="Contains" value="contains"{% ifequal filter_data.filter_criteria 'contains' %} selected="selected"{% endifequal %}>Contains</option>
                        <option label="Equal to" value="equal"{% ifequal filter_data.filter_criteria 'equal' %} selected="selected"{% endifequal %}>Equal to</option>
                        <option label="Not Equal To" value="not_equal"{% ifequal filter_data.filter_criteria 'not_equal' %} selected="selected"{% endifequal %}>Not Equal To</option>
                        <option label="Greater Than or Equal to" value="greater_equal"{% ifequal filter_data.filter_criteria 'greater_equal' %} selected="selected"{% endifequal %}>Greater Than or Equal to</option>
                        <option label="Greater Than" value="greater"{% ifequal filter_data.filter_criteria 'greater' %} selected="selected"{% endifequal %}>Greater Than</option>
                        <option label="Less Than" value="less"{% ifequal filter_data.filter_criteria 'less' %} selected="selected"{% endifequal %}>Less Than</option>
                        <option label="Less Than or Equal to" value="less_equal"{% ifequal filter_data.filter_criteria 'less_equal' %} selected="selected"{% endifequal %}>Less Than or Equal to</option>
                        <option label="Null / Empty / Unassigned" value="is_null"{% ifequal filter_data.filter_criteria 'is_null' %} selected="selected"{% endifequal %}>Null / Empty / Unassigned</option>
                    </select>
                </td>
                <td>
                    <input name="filter_text" type="text" size="30" value="{{ filter_data.filter_text }}"/>
                </td>
            </tr>
            <tr>
                <th>Order Results By:</th>
                <td>
                    <select name="order_by_1">
                        <option label="ID" value="trac_ticket_id"{% ifequal filter_data.order_by_1 'trac_ticket_id' %} selected="selected"{% endifequal %}>ID</option>
                        <option label="Title" value="title"{% ifequal filter_data.order_by_1 'title' %} selected="selected"{% endifequal %}>Title</option>
                        <option label="Description" value="description"{% ifequal filter_data.order_by_1 'description' %} selected="selected"{% endifequal %}>Description</option>
                        <option label="Status" value="status"{% ifequal filter_data.order_by_1 'status' %} selected="selected"{% endifequal %}>Status</option>
                        <option label="Creation Date" value="creation_date"{% ifequal filter_data.order_by_1 'creation_date' %} selected="selected"{% endifequal %}>Creation Date</option>
                    </select>
                    then
                </td>
                <td>
                    <select name="order_by_2">
                        <option label="ID" value="trac_ticket_id"{% ifequal filter_data.order_by_2 'trac_ticket_id' %} selected="selected"{% endifequal %}>ID</option>
                        <option label="Title" value="title"{% ifequal filter_data.order_by_2 'title' %} selected="selected"{% endifequal %}>Title</option>
                        <option label="Description" value="description"{% ifequal filter_data.order_by_2 'description' %} selected="selected"{% endifequal %}>Description</option>
                        <option label="Status" value="status"{% ifequal filter_data.order_by_2 'status' %} selected="selected"{% endifequal %}>Status</option>
                        <option label="Creation Date" value="creation_date"{% ifequal filter_data.order_by_2 'creation_date' %} selected="selected"{% endifequal %}>Creation Date</option>
                    </select>
                </td>
                <td>
                    <label>
                        <input type="radio" name="order" value="ascending" {% ifnotequal filter_data.order 'descending' %}checked="checked"{% endifnotequal %}/> Ascending
                    </label>
                    <label>
                        <input type="radio" name="order" value="descending" {% ifequal filter_data.order 'descending' %}checked="checked"{% endifequal %}/> Descending
                    </label>
                </td>
            </tr>
            <tr>
                <td colspan="3" align="right">
                    <input name="submit" type="submit" id="submit" value="Apply Filter / Order" />&nbsp;
                    <a href=''><button>Remove Filter / Order</button></a>
                </td> 
            </tr>
        </table> 
    </form>
</div>